app/routes.php
<?php

// Display all SQL executed in Eloquent
Event::listen('illuminate.query', function($query) {
    // var_dump($query);
});


// Api Routes
Route::group(['domain' => 'api.labelai.com'], function () {

    Route::any('/', function() {
        return Response::json('Welcome to API ' . Config::get('settings.api.version'));
    });

    Route::group(['prefix' => Config::get('settings.api.version')], function () {

        $method = Request::method();
        if (Request::isMethod('get')) {
            //get access_token
            Route::get('auth', function() {
                $auth = new \ApiController();
                return $auth->auth();
            });
            //get access_token
            Route::get('bwauth', function() {
                $auth = new \ApiController();
                return $auth->bwauth();
            });

            //get bw query
            Route::get('bwquery', function() {
                $auth = new \ApiController();
                return $auth->bwquery();
            });
        } elseif (Request::isMethod('post')) {
            //sentimental query
            Route::post('check', function() {
                $auth = new \ApiController();
                return $auth->check();
            });

            Route::post('postag', function() {
                $auth = new \ApiController();
                return $auth->postag();
            });

            Route::post('images', function() {
                $auth = new \ApiController();
                return $auth->images();
            });
        } else {
            return Response::json('Method not allowed.');
        }
    });
});


//Route::get('dbmigrate', 'DbmigrateController@index');
// Guest Routes
Route::group(array('before' => 'guest'), function() {
//    Route::get('auth/register', array('as' => 'auth.register', 'uses' => 'AuthController@getRegister'));
//    Route::post('auth/register', array('as' => 'auth.register', 'uses' => 'AuthController@postRegister'));

    Route::get('auth/login', array('as' => 'auth.login', 'uses' => 'AuthController@getLogin'));
    Route::post('auth/login', array('as' => 'auth.login', 'uses' => 'AuthController@postLogin'));
});

// Member Routes
Route::group(array('before' => 'auth'), function() {


    /**
     * Home
     */
    Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));

    Route::any('/image', array('as' => 'google', 'uses' => 'HomeController@google'));
    Route::any('/image/update', array('as' => 'google.update', 'uses' => 'HomeController@googleUpdate'));

    Route::get('/cacheflush', function() {
        Cache::flush();

        return Redirect::back();
    });

    // Ajax Routes
    Route::post('traine', array('as' => 'traine', 'uses' => 'HomeController@addTraine'));
    Route::post('analysis', array('as' => 'analysis', 'uses' => 'HomeController@showAnalysis'));
    Route::post('learned', array('as' => 'learned', 'uses' => 'HomeController@getLearned'));

    /**
     * Auth
     */
    Route::get('auth/logout', array('as' => 'auth.logout', 'uses' => 'AuthController@getLogout'));

    Route::get('auth/changepassword', array('as' => 'auth.changepassword', 'uses' => 'AuthController@getChangepassword'));
    Route::post('auth/changepassword', array('as' => 'auth.changepassword', 'uses' => 'AuthController@postChangepassword'));

    /**
     * Sentimental
     */
    Route::post('sentimental/create', array('as' => 'sentimental.create', 'uses' => 'SentimentalController@create'));
    Route::resource('sentimental', 'SentimentalController', array('except' => array('show')));

    /**
     * Account
     */
    Route::resource('account', 'AccountController', array('except' => array('show')));

    /**
     * Sources -> {Comments}
     */
    Route::resource('invoice', 'InvoiceController', array('only' => array('index', 'show')));

    /**
     * Domain
     */
    Route::post('domain/tags', array('as' => 'domain.tags', 'uses' => 'DomainController@tags'));
    Route::any('domain/create', array('as' => 'domain.create', 'uses' => 'DomainController@create'));
    Route::resource('domain', 'DomainController', array('except' => array('show')));

    /**
     * Statistics
     */
    Route::get('statistics', array('as' => 'statistics', 'uses' => 'StatisticsController@index'));
    Route::post('statistics/analysis', array('as' => 'statistics.analysis', 'uses' => 'StatisticsController@analysis'));
    Route::post('statistics/chart', array('as' => 'statistics.chart', 'uses' => 'StatisticsController@chart'));
    Route::post('statistics/unprocessed', array('as' => 'statistics.unprocessed', 'uses' => 'StatisticsController@unprocessed'));

    /**
     * Ticket
     */
    Route::resource('ticket', 'TicketController');
    Route::post('ticket/{ticket}/reply', array('as' => 'ticket.reply', 'uses' => 'TicketController@reply'));

    /**
     * Filter
     */
    Route::resource('filter', 'FilterController', array('except' => array('show')));
    Route::post('filter/tags', array('as' => 'tweets', 'uses' => 'FilterController@tags'));

    /**
     * Tag
     */
    Route::resource('tag', 'TagController', array('except' => array('show')));

    /**
     * taguploads -> {Tags}
     */
    Route::post('tag/remove', array('as' => 'tag.remove', 'uses' => 'TagUploadController@removeTag')); //Acception
    Route::post('tag/add', array('as' => 'tag.add', 'uses' => 'TagUploadController@addTag')); //Acception
    Route::post('tagupload/delete', array('as' => 'tagupload.delete', 'uses' => 'TagUploadController@delete'));
    Route::put('tagupload/create', 'TagUploadController@store');
    Route::any('tagupload/add', array('as' => 'tagupload.add', 'uses' => 'TagUploadController@add'));
    Route::post('tagupload/save', array('as' => 'tagupload.save', 'uses' => 'TagUploadController@updateAjaxTag'));
    Route::resource('tagupload', 'TagUploadController');

    /**
     * Admin
     */
    Route::group(array('before' => 'admin'), function() {
        // User route
        Route::resource('user', 'UserController');
    });


    /**
     * Users
     */
    Route::resource('userlogs', 'UserLogController', array('only' => array('index', 'show')));
    Route::get('userlogs/user/{user_id}', array('as' => 'userlogs.userlog', 'uses' => 'UserLogController@userlog'));
    Route::get('updatelogs', 'UserLogController@updatelogs');

    /**
     * Comments
     */
    Route::any('comments', array('as' => 'comments.index', 'uses' => 'CommentController@index'));
    Route::any('comments/search', array('as' => 'comments.search', 'uses' => 'CommentController@search'));
    Route::any('comments/publish', array('as' => 'comments.publish', 'uses' => 'CommentController@publish'));

    /**
     * Sources -> {Comments}
     */
    Route::resource('source', 'SourceController', array('except' => array('show')));

    /**
     * uploads -> {Sources}
     */
    Route::put('upload/create', 'UploadController@store');
    Route::post('upload/save', array('as' => 'upload.save', 'uses' => 'UploadController@update'));
    Route::resource('upload', 'UploadController');

    /**
     * Brandwatch -> {API}
     */
    Route::get('bwatch/{id}/edit', array('as' => 'bwrules.show', 'uses' => 'BwrulesController@show'));
    Route::get('bwatch/{id}/pause', array('as' => 'bwatch.pause', 'uses' => 'BwatchController@pause'));
    Route::get('bwatch/{id}/run', array('as' => 'bwatch.run', 'uses' => 'BwatchController@run'));
    Route::resource('bwatch', 'BwatchController');

    Route::post('bwrules/{id}/', array('as' => 'bwrules.update', 'uses' => 'BwrulesController@update'));
    Route::get('bwrules/queries/', array('as' => 'bwrules.queries', 'uses' => 'BwrulesController@bwQueryCall'));
    Route::get('bwrules/{id}/pause', array('as' => 'bwrules.pause', 'uses' => 'BwrulesController@pause'));
    Route::get('bwrules/{id}/run', array('as' => 'bwrules.run', 'uses' => 'BwrulesController@run'));
    Route::resource('bwrules', 'BwrulesController');
    
    Route::any('/js', function() {
        print('Yazılımın doğru çalışabilmesi için lütfen Javascript izinlerini aktif olarak değiştirin. <br>  '
                . '<a target="_settings "href="https://www.google.com.tr/search?q=javascript+ayarlar%C4%B1n%C4%B1+a%C3%A7ma&btnG=Search">Nasıl yapılır?</a>'
                . '<br><br><a href="/"> Giriş sayfasına dönün.</a>');
        exit;
    });
});

app/models/Bwatch.php
<?php

use Illuminate\Database\Eloquent\SoftDeletingTrait;

class Bwatch extends \Eloquent {

    use SoftDeletingTrait;

    protected $softDelete = true;
    protected $table = 'bwatchs';
    protected $dates = ['deleted_at'];
    protected $fillable = [
        'account_id',
        'user_id',
        'username',
        'bw_token',
        'expires_in',
        'status',
        'is_active',
        'token_type',
        'scope',
        'json',
        'created_by',
        'updated_by',
        'created_by',
        'updated_by',
        'created_at',
        'updated_at',
        'deleted_at'
    ];
    protected static $settings = null;

    /**
     * A many-to-one relationship user to account
     *
     * @return mix
     */
    public function account() {
        return $this->belongsTo('Account');
    }

    /**
     * A one-to-one relationship user to users
     *
     * @return mix
     */
    public function users() {
        return $this->belongsTo('User');
    }

    /**
     * A one-to-one relationship bwaccounts_to bwrules
     *
     * @return mix
     */
    public function bwrules() {
        return $this->hasMany('Bwrule', 'bwatch_id');
    }

    /**
     * A one-to-one relationship bwaccounts_to bwtats
     *
     * @return mix
     */
    public function bwstats() {
        return $this->hasMany('BwruleStat', 'bwatch_id');
    }

    /**
     * Engagement Status
     *
     * @return boolen
     */
    public function is_connected() {
        if ($this->getAttribute('status') == '1')
            return true;
        else
            return false;
    }

    /**
     * Activation Status
     *
     * @return boolen
     */
    public function is_active() {
        if ($this->getAttribute('is_active') == '1')
            return true;
        else
            return false;
    }

    /**
     * Get Settings
     *
     * @return boolen
     */
    public function getSettings() {
        self::$settings = json_decode($this->getAttribute('json'), true);
        return self::$settings;
    }

    /**
     * Get BW Account Details
     *
     * @return boolen
     */
    public function getBWAccount() {
        if ($this->settings) {
            return self::getSettings()["links"]['client'];
        }
        return array();
    }

    /**
     * Get BW Account Project Details
     *
     * @return boolen
     */
    public function getProjects() {
        if ($this->settings) {
            return self::getSettings()['links']['projects'];
        }
        return array();
    }

}

app/views/plugins/bwatch/rules/create.blade.php
@extends('layouts.master')

@section('title', 'Yeni Kural Ekle')


@section('content')
<div class="page-header" id="create">
    <h2>Yeni Kural Ekle</h2>
</div>

{{ Form::open(array('role' => 'form', 'route' => array('bwrules.store', Input::get('id')), 'method' => 'POST', 'id'=>'create')) }}
{{ Form::hidden('bwatch_id', Input::get('id')) }}

<div {{ $errors->has('name') ? 'class="form-group has-error"' : 'class="form-group"' }} >
    {{ Form::label('name', 'Kural Adı') }}
    {{ Form::text('name', Input::old('name'), array('class' => 'form-control', 'placeholder' => 'Kural adını giriniz')) }}
    {{ $errors->has('name') ? $errors->first('name', '<span class="text-danger">:message</span>') : '' }}
</div>

<div {{ $errors->has('datamark') ? 'class="form-group has-error"' : 'class="form-group"' }} >
    {{ Form::label('datamark', 'Data işareti') }}
    {{ Form::text('datamark', Input::old('datamark'), array('class' => 'form-control', 'placeholder' => 'Güncellenen datalar için bir işaret giriniz')) }}
    {{ $errors->has('datamark') ? $errors->first('datamark', '<span class="text-danger">:message</span>') : '' }}
</div>

<div {{ $errors->has('fromdate') ? 'class="form-group has-error"' : 'class="form-group"' }} >

    {{ Form::label('fromdate', 'Data süresi:') }}
    {{ Form::select('fromdate', ['0'=>'Tüm data','1'=>'Bu günden itibaren'], 0, array('id'=>'fromdate', 'class' => 'form-control', 'placeholder' => 'Lütfen bir değer seçin')) }}
    {{ $errors->has('fromdate') ? $errors->first('fromdate', '<span class="text-danger">:message</span>') : '' }}

    <small class="help-block">Bu bölümden hangi tarihten sonraki dataların dikkate alınacağını belirleyebilirsiniz.</small>
</div>

@if($projects)
{{ Form::hidden('bwtoken', $bwtoken, array('id'=>'bwtoken')) }}

<!--queries-->
@if($queries) 
@foreach($queries as $val => $key)
{{ Form::hidden('q_'.$val, $key, array('id'=>'q_'.$val)) }}
@endforeach
@endif
<!--queriesEND-->

{{ Form::label('project','Proje:')}}
{{ $errors->has('project') ? $errors->first('project', '<span class="text-danger">Bu alan gereklidir.</span>') : '' }}
<div  id="sourceContainer" {{ $errors->has('project') ? 'class="form-group has-error"' : 'class="form-group"' }} >
    {{ Form::select('project', [''=>'Lütfen bir proje seçin'] + $projects, null, array('id'=>'project', 'class' => 'form-control', 'placeholder' => 'Lütfen işlem yapılacak projeyi seçin')) }}
    <small class="help-block">Bu bölümden BW projelerinize ulaşabilirsiniz.<br/> <span class="text-warning">Not: Eğer bir kural eklenir ve daha sonra proje kaldırılırsa, kuralda otomatik olarak kaldırılır.</span></small>
</div>
@endif
<div class="center-block row">

    <div id="queriesContainer"  class="col-md-8" style="display: none">

        <div class="form-group col-sm-5">
            <select name="from[]" id="search" class="form-control" size="6" multiple="multiple">  
            </select>
        </div>

        <div class="form-group col-sm-2">
            <button type="button" id="search_rightAll" rel="move" class="btn btn-block bg-success"><i class="glyphicon glyphicon-forward"></i></button>
            <button type="button" id="search_rightSelected" rel="move" class="btn btn-block bg-success"><i class="glyphicon glyphicon-chevron-right"></i></button>
            <button type="button" id="search_leftSelected" rel="move" class="btn btn-block bg-success"><i class="glyphicon glyphicon-chevron-left"></i></button>
            <button type="button" id="search_leftAll" rel="move" class="btn btn-block bg-success"><i class="glyphicon glyphicon-backward"></i></button>
        </div>

        <div class="form-group col-sm-5">
            <select name="to[]" id="search_to" class="form-control" size="6" multiple="multiple"></select>
        </div>

        <small class="help-block col-md-8">Bu bölümden hangi Query sonuçlarının etkilenmesini istediğinizi seçenebilirsiniz. <br/> <span class="text-warning"><span id="count">0</span> adet Query seçildi.</span></small>
    </div>

    <div id="domainContainer" class="col-md-4" style="display: none">
        <div {{ $errors->has('domain') ? 'class="form-group has-error"' : 'class="form-group"' }} >
            {{ Form::label('domain', 'Domain:') }}
            {{ Form::select('domain', [''=>'Lütfen bir domain seçin'] + $domains, null, array('id'=>'domain', 'class' => 'form-control', 'placeholder' => 'Lütfen işlem yapılacak domaini seçin')) }}
            {{ $errors->has('domain') ? $errors->first('domain', '<span class="text-danger">:message</span>') : '' }}
        </div>
    </div>

    <div id="whenContainer" class="col-md-4" style="display: none; width: 370px;">
        <div class="col-sm-4">
            <div class="form-group">
                {{ Form::label('param1', 'Param (1)', array('class' => '')) }}
                <div class="input-group spinner">
                    {{ Form::text('param1', Input::old('param1', '0'), array('class' => 'form-control input-spinner input-spinner-positive', 'placeholder' => 'Filtre adı giriniz', 'data-min' => 0, 'data-max' => 100, 'readonly')) }}
                    <div class="input-group-btn-vertical">
                        <button class="btn btn-default btn-spinner"><i class="fa fa-caret-up"></i></button>
                        <button class="btn btn-default btn-spinner"><i class="fa fa-caret-down"></i></button>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="form-group">
                {{ Form::label('param2', 'Param (-1)', array('class' => '')) }}
                <div class="input-group spinner">
                    {{ Form::text('param2', Input::old('param2', '0'), array('class' => 'form-control input-spinner input-spinner-negative', 'placeholder' => 'Filtre adı giriniz', 'data-min' => 0, 'data-max' => 100, 'readonly')) }}
                    <div class="input-group-btn-vertical">
                        <button class="btn btn-default btn-spinner"><i class="fa fa-caret-up"></i></button>
                        <button class="btn btn-default btn-spinner"><i class="fa fa-caret-down"></i></button>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="form-group">
                {{ Form::label('param3', 'Param (0)', array('class' => '')) }}
                <div class="input-group spinner">
                    {{ Form::text('param3', Input::old('param3', '100'), array('class' => 'form-control input-spinner input-spinner-neutral', 'placeholder' => 'Filtre adı giriniz', 'data-min' => 0, 'data-max' => 100, 'readonly')) }}
                    <div class="input-group-btn-vertical">
                        <button class="btn btn-default btn-spinner" disabled="disabled"><i class="fa fa-caret-up"></i></button>
                        <button class="btn btn-default btn-spinner" disabled="disabled"><i class="fa fa-caret-down"></i></button>
                    </div>
                </div>
            </div>
        </div>


        <small class="help-block"><span class="text-warning">Not: A,B ve C için belirlenecek değerlerin en yükseği hangisiyse, şart olarak o değer ve üstü geçerli olur.<br> Eğer en yüksek C/ Nötr ise sonraki en büyük değer geçerli olur. <br> Eğer, A ve B sıfırsa, C/Nötr 100% olan eşitliklere bakılır. </span></small>


    </div>

    <div class="col-md-6" id="actionContainer" style="display: none;">
        <div {{ $errors->has('action') ? 'class="form-group has-error"' : 'class="form-group"' }} >
            {{ Form::label('action', 'İşlem:') }}
            {{ Form::select('action', [''=>'Lütfen bir işlem seçin'] + $actions, null, array('id'=>'action', 'class' => 'form-control', 'placeholder' => 'Lütfen yapılacak işlemi seçin')) }}
            {{ $errors->has('action') ? $errors->first('action', '<span class="text-danger">:message</span>') : '' }}
        </div>
        <small class="help-block">Bu bölümden yukarıdaki kriterlere uyan datalar için nasıl bir işlem yapmak istediğinizi seçebilirsiniz.</small>
    </div>


    <div class="col-md-6" id="categoriesContainer" style="display: none;">
        <div {{ $errors->has('categories') ? 'class="form-group has-error"' : 'class="form-group"' }} >
            <input type="hidden" id="categorydata" value="">
                {{ Form::label('category', 'Kategoriler:') }}
                {{ Form::select('category', [''=>'Lütfen bir kategori seçin'], null, array('id'=>'category', 'class' => 'form-control', 'placeholder' => 'Lütfen bir kategori seçin')) }}
        </div>
        <small class="help-block">Bu bölümden dataların kategorilerini değiştirebilirsiniz.</small>
    </div>

    <div class="col-md-12" id="subcategoriesContainer" style="display: none;">
        {{ Form::label('subcategories', 'Alt Kategoriler:') }}
        <div {{ $errors->has('subcategories') ? 'class="form-group has-error"' : 'class="form-group"' }} >
        </div>
        <small class="help-block">Bu bölümden dataların hangi alt kategorilere ekleneceğini seçebilirsiniz.</small>
    </div>

    <div class="col-md-6" id="sentimentContainer" style="display: none;">
        <div {{ $errors->has('sentiment') ? 'class="form-group has-error"' : 'class="form-group"' }} >
            {{ Form::label('sentiment', 'Sentiment:') }}
            {{ Form::select('sentiment', ['1'=>'Olumlu','-1'=>'Olumsuz','0'=>'Notr'], 0, array('id'=>'sentiment', 'class' => 'form-control', 'placeholder' => 'Lütfen bir değer seçin')) }}
            {{ $errors->has('sentiment') ? $errors->first('sentiment', '<span class="text-danger">:message</span>') : '' }}
        </div>
        <small class="help-block">Bu bölümden dataların duygusal analizlerini değiştirebilirsiniz.</small>
    </div>

    <div class="col-md-6" id="deleteContainer" style="display: none;">
        <div {{ $errors->has('delete') ? 'class="form-group has-error"' : 'class="form-group"' }} >
            {{ Form::label('delete', 'Silme Onayı:') }}

            {{ Form::checkbox('delete', 1, null, ['class' => '','id'=>'delete']) }}  Evet, onaylıyorum.
            <small class="help-block"><span class="text-danger">Yukarıdaki şartlara uyan datalar silinecek, emin misiniz?</span></small>

            {{ $errors->has('delete') ? $errors->first('delete', '<span class="text-danger">:message</span>') : '' }}
        </div>
    </div>

    <div class="col-md-6 form-group" id="tagContainer" style="display: none;">

        <div {{ $errors->has('tags') ? 'class="form-group has-error"' : 'class="form-group"' }} >
            {{ Form::label('tags', 'Etiketler:') }}
        </div>
        <small class="help-block">Bu bölümden dataların nasıl etiketleneceğini belirtebilirsiniz.<br><span class="text-warning">En fazla 4 adet etiket ekleyebilirsiniz. </span></small>
    </div>

</div>

<div class="col-md-12">
    <hr/>
    {{ Form::submit('Ekle', array('class' => 'btn btn-info', 'id'=>'save')); }}
    {{ HTML::linkRoute('bwatch.edit', 'İptal', array($bwatch->id), array('class' => 'btn btn-default', 'title' => 'İptal')) }}
    {{ Form::close() }}
</div>
@stop



@section('script')
{{ HTML::script('/assets/js/bwrules.js') }}
@stop

app/views/plugins/bwatch/rules/index.blade.php
@extends('layouts.master')

@section('title', 'Brandwatch')

@section('content')

<div class="page-header" id="user">
    <h2>Brandwatch</h2>
    <p class="help-block right"><a href="http://www.brandwatch.com/" target="_blank">Brandwatch</a> bölümüne hoş geldiniz. 
        Brandwatch projelerinizi codexAI API üzerinden bağlayabilir ve birlikte uyum içinde çalışmasını sağlayabilirsiniz.</p>
</div>


<div class="row">
    <div class="col-md-6">
        <div class="input-group col-md-8">
            {{ Form::open(array('bwrules' => 'form', 'route' => array('bwrules.index'), 'method' => 'POST', 'class' => '')) }}
            <div class="input-group">
                {{ Form::text('q', Input::get('q'), array('class' => 'form-control', 'placeholder' => 'Hesap adı girin..')) }}
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"><span class="fa fa-search"></span></button>
                </span>
            </div>
            {{ Form::close() }}
        </div>
    </div>


    <div class="col-md-6">
        <div class="pull-right">
            @if( $user->role == 'admin'|| is_super_admin())
            <a href="{{ URL::route('bwrules.create', array('id'=>$bwatch->id)) }}" class="btn btn-default"><span class="fa fa-plus"></span> Yeni Kural Ekleyin</a>   

            @endif
        </div>
    </div>


</div>
<hr/>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>No</th>
            <th>Kural Adı</th>
            <th>Email</th>
            <th>Bağlantı</th>
            <th>Durum</th>
            <th>Geçerlilik Tarihi</th>
            <th>Oluşturma Tarihi</th>
            <th>Son Güncelleme</th>
            <th class="text-right">İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @if (count($bwrules) > 0)
        @foreach ($bwrules as $bwrule)

        <?php
        switch ($bwrule->is_active) {
            case '0': $label_active = 'label-primary';
                $text_active = 'Bağlantı yok';
                break;
            case '1': $label_active = 'label-success';
                $text_active = 'Bağlandı';
                break;
            default: $label_active = 'label-primary';
                $text_active = 'Bağlantı yok';
        }


        switch ($bwrule->status) {
            case '0': $label_status = 'label-primary';
                $text_status = 'Çalışmıyor';
                break;
            case '1': $label_status = 'label-success';
                $text_status = 'Çalışıyor';
                break;
            default: $label_status = 'label-primary';
                $text_status = 'Çalışmıyor';
        }
        ?>

        <tr>

            <td><span class="label label-default"># {{ $bwrule->id }}</span></td>
            <td><span class="label label-success">{{ $bwrule->name }}</span></td>
            <td><span class="label label-default">{{ Bwatch::find($bwrule->bwatch_id)->username }}</span></td>
            <td><span class="label {{$label_active}}">{{$text_active}}</span></td>
            <td><span class="label {{$label_status}}">{{ $text_status }}</span></td>
            @if($bwatch->status == 1)
            <td><span class="label label-default">{{ \Carbon\Carbon::createFromTimestamp($bwatch->created_at->getTimestamp())->addSeconds($bwrule->expires_in) }}</span></td>
            @else
            <td><span class="label label-primary">{{ $text_status }}</span></td>
            @endif

            <td><span class="label label-default">{{ $bwrule->created_at }}</span></td>
            <td><span class="label label-default">{{ $bwrule->updated_at }}</span></td>


            <td class="text-right" width="150">
                {{ Form::open(array('role' => 'form', 'route' => array('bwrules.destroy', $bwrule->id), 'method' => 'DELETE', 'class' => 'pull-right form-delete', 'id' => $bwrule->id)) }}


                <!--pause/play-->
                @if( $user->role == 'admin'|| is_super_admin())

                @if($bwrule->status == 1)
                {{ HTML::linkRoute('bwrules.pause', '', array($bwrule->id), array('class' => 'btn-sm btn-danger fa fa-pause tooltip-show', 'title' => 'Durdur')) }}
                @else
                {{ HTML::linkRoute('bwrules.run', '', array($bwrule->id), array('class' => 'btn-sm btn-info fa fa-play tooltip-show', 'title' => 'Çalıştır')) }}
                @endif

                @endif
                <!--pause/play end-->


                {{ HTML::linkRoute('bwrules.edit', '', array($bwrule->id), array('class' => 'btn-sm btn-default fa fa-cogs tooltip-show', 'title' => 'Güncelle')) }}

                {{ Form::button('', array('type' => 'submit', 'class' => 'btn btn-sm btn-primary fa fa-trash-o tooltip-show', 'title' => 'Sil')) }}
                {{ Form::close() }}
            </td>

        </tr>
        @endforeach
        @else
        <tr>
            <td colspan="8" class="text-center"><small><em>Kayıt bulunamadı!</em></small></td>
        </tr>
        @endif
    </tbody>
</table>

{{ $bwrules->links() }}
@stop